esphome:
  name: kitchen-temp

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Kitchen Temp Fallback Hotspot"
    password: !secret fallback_wifi_password

captive_portal:

i2c:
  sda: 4
  scl: 5
  scan: True
  id: bus_a

sensor:
  - platform: sht3xd
    address: 0x44
    temperature:
      name: "Kitchen Temperature"
    humidity:
      name: "Kitchen Humidity"
    update_interval: 60s
