esphome:
  name: bedroom-temp

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Bedroom Temp Fallback Hotspot"
    password: !secret fallback_wifi_password

captive_portal:

sensor:
  - platform: dht
    pin: D2
    model: DHT22
    temperature:
      name: "Bedroom Temperature"
    humidity:
      name: "Bedroom Humidity"
    update_interval: 60s
